name: .NET Core API CI/CD

on:
  push:
    paths:
      - 'CustomerOrderApi/**'
  pull_request:
    paths:
      - 'CustomerOrderApi/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CustomerOrderApi

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal
