name: angular app ci cd 

on:
  push:
    branches:
      - main
    paths:
      - 'my-profile-ui/**'
  pull_request:
    branches:
      - main
    paths:
      - 'my-profile-ui/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-profile-ui

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        #working-directory: my-profile-ui
        run: npm ci

      - name: Run Testa
        run: npm run test -- --watch=false --browsers=ChromeHeadlessNoSandbox

      - name: Build the application
        run: npm run build --configuration=production

      - name: 💾 Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: my-profile-ui/dist/my-profile-ui/

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./dist/my-profile-ui
      #     publish_branch: gh-pages